# Generated by Django 3.2.8 on 2022-07-23 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220707_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 54, 10, 354826)),
        ),
        migrations.AlterField(
            model_name='articleprime',
            name='body',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='articleprime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 54, 10, 355826)),
        ),
    ]
