# Generated by Django 3.2.8 on 2022-07-23 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220723_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 17, 4, 11, 622320)),
        ),
        migrations.AlterField(
            model_name='articleprime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 17, 4, 11, 623980)),
        ),
    ]
