# Generated by Django 3.2.8 on 2022-06-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgIllustration',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
