# Generated by Django 3.2.8 on 2022-06-16 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220616_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 20, 39, 41, 708649)),
        ),
        migrations.AlterField(
            model_name='article',
            name='imgIllustration',
            field=models.FileField(default='media/logo.png', upload_to='media/'),
        ),
    ]
