# Generated by Django 3.2.8 on 2022-06-21 22:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20220620_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePrime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=100000000000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 21, 23, 18, 6, 376376))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Article of the week',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 23, 18, 6, 373385)),
        ),
        migrations.DeleteModel(
            name='ArticleOfTheWeek',
        ),
    ]
