# Generated by Django 3.2.8 on 2022-07-07 11:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20220621_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 12, 6, 25, 629600)),
        ),
        migrations.AlterField(
            model_name='articleprime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 12, 6, 25, 629911)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='media/profiles/img_avatar2.png', upload_to='media/profiles/')),
                ('age', models.SmallIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
